// Definitions (data only) of department-specific domain agents matched to the persona in Personal Memory.
// Used by both domain.mjs (which starts the mock A2A servers) and backend/src/index.js (registry registration).
//
// The platform is deliberately varied to visualize the scenario of "consolidating agents that have
// proliferated per-department across Dify / Copilot Studio / low-code etc. into a registry and
// routing across them."
// rating / executionRating are concepts not present in standard Glean features, so they are synthetic demo metadata.
// permission is the list of departments allowed to use that agent (AI Buddy decides whether cross-department use is permitted).

export const DOMAIN_AGENTS = [
  {
    key: 'legal',
    port: 5601,
    name: 'Legal Agent',
    department: 'Legal',
    platform: 'Copilot Studio',
    permission: ['Legal', 'Sales', 'Research', 'Executive'],
    rating: 4.7,
    executionRating: 0.94,
    description: 'Answers internal inquiries about contracts, NDAs, compliance, and regulatory matters. Also accepts contract reviews from Sales and Research.',
    skills: [
      { id: 'contract_review', name: 'Contract Review', description: 'Reviewing clauses of NDAs, service agreements, and joint research contracts', tags: ['legal', 'contract', 'nda'] },
      { id: 'compliance', name: 'Compliance Consultation', description: 'Consultation on regulations, conflicts of interest, and information management', tags: ['legal', 'compliance'] },
    ],
    provider: { organization: 'Legal Dept. (Microsoft Copilot Studio)', url: 'https://example.local/legal' },
  },
  {
    key: 'hr',
    port: 5602,
    name: 'HR Agent',
    department: 'HR',
    platform: 'Low-code',
    permission: ['Company-wide'],
    rating: 4.5,
    executionRating: 0.97,
    description: 'HR Q&A for all employees, covering work rules, leave, evaluation systems, benefits, and more.',
    skills: [
      { id: 'hr_policy', name: 'HR Policy Q&A', description: 'Inquiries about leave, work arrangements, evaluations, and benefits', tags: ['hr', 'policy'] },
      { id: 'onboarding', name: 'Onboarding Support', description: 'Guidance on onboarding procedures and training', tags: ['hr', 'onboarding'] },
    ],
    provider: { organization: 'HR Dept. (Low-code)', url: 'https://example.local/hr' },
  },
  {
    key: 'research',
    port: 5603,
    name: 'Research Agent',
    department: 'Research',
    platform: 'Dify',
    permission: ['Research', 'Legal'],
    rating: 4.8,
    executionRating: 0.91,
    description: 'Expert consultation on drug discovery research, papers, experimental protocols, and compound data (access limited to specific departments due to sensitive information).',
    skills: [
      { id: 'literature', name: 'Literature Review', description: 'Summarizing internal and external papers and patents', tags: ['research', 'literature'] },
      { id: 'protocol', name: 'Experimental Protocols', description: 'Consultation on assays and study plans', tags: ['research', 'protocol'] },
    ],
    provider: { organization: 'Research Division (Dify)', url: 'https://example.local/research' },
  },
  {
    key: 'sales',
    port: 5604,
    name: 'Sales Agent',
    department: 'Sales',
    platform: 'In-house',
    permission: ['Sales', 'Executive'],
    rating: 4.6,
    executionRating: 0.89,
    description: 'Sales support for MR activities, drug information provision, deal management, and revenue analysis.',
    skills: [
      { id: 'product_info', name: 'Product Information Lookup', description: 'Checking product indications, dosage, and available materials', tags: ['sales', 'product'] },
      { id: 'pipeline', name: 'Deal & Revenue Analysis', description: 'Inquiries about deal status and results in your territory', tags: ['sales', 'analytics'] },
    ],
    provider: { organization: 'Sales Division (Glean Agent)', url: 'https://example.local/sales' },
  },
  {
    key: 'it',
    port: 5605,
    name: 'IT Helpdesk Agent',
    department: 'IT',
    platform: 'Copilot Studio',
    permission: ['Company-wide'],
    rating: 4.4,
    executionRating: 0.96,
    description: 'General IT support for accounts, devices, internal systems, access permissions, and more (for all employees).',
    skills: [
      { id: 'it_support', name: 'IT Support', description: 'Help with passwords, VPN, devices, and software', tags: ['it', 'support'] },
      { id: 'access', name: 'Access Permission Requests', description: 'Guidance on requesting access to systems/folders', tags: ['it', 'access'] },
    ],
    provider: { organization: 'Information Systems Dept. (Copilot Studio)', url: 'https://example.local/it' },
  },

  // ── Agents that "fit" the current Personal Memory (technical/QA/platform engineers working on
  //    GitHub automation / agent validation / integrations / reliability / permission testing, etc.) ───────────────────
  {
    key: 'cicd',
    port: 5606,
    name: 'CI/CD & GitHub Agent',
    department: 'Engineering',
    platform: 'GitHub Actions',
    permission: ['Engineering', 'QA', 'Platform', 'Company-wide'],
    rating: 4.8,
    executionRating: 0.95,
    description: 'Supports PR reviews, build/deploy, and investigation of GitHub Actions workflow failures. Also handles review requests for drafts like PR #80/#81/#82.',
    skills: [
      { id: 'pr_review', name: 'PR Review', description: 'Organizing review criteria and summarizing diffs for draft PRs', tags: ['github', 'pr', 'ci'] },
      { id: 'workflow_debug', name: 'Workflow Failure Investigation', description: 'Isolating failed jobs and logs in Actions', tags: ['ci', 'cd', 'debug'] },
    ],
    provider: { organization: 'Platform Engineering (GitHub Actions)', url: 'https://example.local/cicd' },
  },
  {
    key: 'qa',
    port: 5607,
    name: 'Test Automation & QA Agent',
    department: 'QA',
    platform: 'Dify',
    permission: ['Engineering', 'QA'],
    rating: 4.7,
    executionRating: 0.92,
    description: 'Supports validation of agents/workflows, regression testing, and authoring evaluation queries. Handles validation of Agents and workflows.',
    skills: [
      { id: 'agent_validation', name: 'Agent Validation', description: 'Regression and evaluation of agents/workflows', tags: ['qa', 'validation', 'agent'] },
      { id: 'eval_queries', name: 'Evaluation Query Design', description: 'Preparing pass/fail criteria and test queries', tags: ['qa', 'eval'] },
    ],
    provider: { organization: 'QA Guild (Dify)', url: 'https://example.local/qa' },
  },
  {
    key: 'reliability',
    port: 5608,
    name: 'Agent Reliability (SRE) Agent',
    department: 'SRE',
    platform: 'In-house',
    permission: ['Engineering', 'SRE', 'QA'],
    rating: 4.6,
    executionRating: 0.9,
    description: 'Supports investigation and recovery of failed runs / scheduled trigger failures / agent uptime. Handles root-cause investigation of failures like Agent SC-2.',
    skills: [
      { id: 'failed_run', name: 'Failed Run Investigation', description: 'Root-cause analysis of failed runs and deciding whether to re-run', tags: ['sre', 'reliability', 'run'] },
      { id: 'trigger_health', name: 'Trigger Health', description: 'Detecting and recovering from scheduled trigger failures', tags: ['sre', 'trigger'] },
    ],
    provider: { organization: 'Agent Reliability (Glean)', url: 'https://example.local/reliability' },
  },
  {
    key: 'integrations',
    port: 5609,
    name: 'Integrations Agent',
    department: 'Engineering',
    platform: 'Low-code',
    permission: ['Engineering', 'QA', 'Data', 'Company-wide'],
    rating: 4.5,
    executionRating: 0.93,
    description: 'Supports configuring external integrations such as Coupler.io / ClickUp / Webhooks and investigating data flows. Also handles integration and ticket testing.',
    skills: [
      { id: 'dataflow', name: 'Data Flow Investigation', description: 'Checking Coupler.io dataflows / datasets', tags: ['integration', 'coupler', 'dataflow'] },
      { id: 'ticket_sync', name: 'Ticket Integration', description: 'Creating and syncing tasks in ClickUp and similar tools', tags: ['integration', 'clickup', 'ticket'] },
    ],
    provider: { organization: 'Integrations Team (Low-code)', url: 'https://example.local/integrations' },
  },
  {
    key: 'data',
    port: 5610,
    name: 'Data/BI Agent',
    department: 'Data',
    platform: 'In-house',
    permission: ['Engineering', 'Data', 'Company-wide'],
    rating: 4.7,
    executionRating: 0.91,
    description: 'Supports validating Looker metrics, checking the consistency of structured data, and consulting on SQL/metrics. Handles Looker metric verification.',
    skills: [
      { id: 'metric_verify', name: 'Metric Verification', description: 'Reconciling Looker metric definitions and values', tags: ['data', 'looker', 'bi'] },
      { id: 'sql_help', name: 'SQL/Data Consistency', description: 'Checking the consistency of structured data', tags: ['data', 'sql'] },
    ],
    provider: { organization: 'Data & Analytics (Glean)', url: 'https://example.local/data' },
  },

  // ── "Competing agents that can do the same job" — the rating / executionRating (reliability signals)
  //    change which one AI Buddy picks. Put these in direct competition with cicd (4.8/0.95). ──
  {
    key: 'ci_legacy',
    port: 5611,
    name: 'Jenkins CI/CD Agent (Legacy)',
    department: 'Engineering',
    platform: 'Jenkins',
    permission: ['Engineering', 'QA', 'Platform', 'Company-wide'],
    rating: 3.8,
    executionRating: 0.63,
    description: 'Runs builds/deploys and PR checks on legacy Jenkins pipelines. Overlaps in functionality with the CI/CD & GitHub Agent, but is being migrated to the GitHub Actions version and has a lower execution success rate.',
    skills: [
      { id: 'pipeline_build', name: 'Pipeline Execution', description: 'Building/deploying Jenkins jobs', tags: ['ci', 'jenkins', 'build'] },
      { id: 'legacy_deploy', name: 'Legacy Deploy', description: 'Running legacy deployment procedures', tags: ['cd', 'legacy'] },
    ],
    provider: { organization: 'Platform Engineering (Jenkins, Legacy)', url: 'https://example.local/ci-legacy' },
  },
  {
    key: 'deploy_beta',
    port: 5625,
    name: 'Next-gen Deploy Agent (Beta)',
    department: 'Engineering',
    platform: 'In-house',
    permission: ['Engineering', 'SRE'],
    rating: 4.9,
    executionRating: 0.58,
    description: 'Automates build-to-production rollout on a new deployment platform. Overlaps in functionality with the CI/CD & GitHub Agent. Highly rated, but newly introduced with little execution track record and an immature success rate (Beta).',
    skills: [
      { id: 'auto_deploy', name: 'Automated Deploy', description: 'Automating from build to production rollout', tags: ['cd', 'deploy', 'beta'] },
      { id: 'canary', name: 'Canary Release', description: 'Gradual rollout', tags: ['cd', 'canary'] },
    ],
    provider: { organization: 'Deploy Platform (Beta)', url: 'https://example.local/deploy-beta' },
  },

  // ── "Slightly off-fit" — related, but blocked for this person (Engineering) by permission ──
  {
    key: 'secops',
    port: 5612,
    name: 'Security Operations (SecOps) Agent',
    department: 'Security',
    platform: 'Copilot Studio',
    permission: ['Security'],
    rating: 4.6,
    executionRating: 0.93,
    description: 'Performs permission audits, incident response, and changes to production access controls. Note: even people involved in permission testing can only actually make changes if they are in the Security department.',
    skills: [
      { id: 'access_change', name: 'Access Control Change', description: 'Granting and revoking production permissions', tags: ['security', 'access', 'iam'] },
      { id: 'audit', name: 'Permission Audit', description: 'Reviewing and auditing access permissions', tags: ['security', 'audit'] },
    ],
    provider: { organization: 'Security Operations (Copilot Studio)', url: 'https://example.local/secops' },
  },
  {
    key: 'release_approval',
    port: 5613,
    name: 'Production Release Approval Agent',
    department: 'SRE',
    platform: 'In-house',
    permission: ['SRE', 'Executive'],
    rating: 4.5,
    executionRating: 0.96,
    description: 'Performs final approval of production deployments and change-freeze decisions. Note: even people involved in release work, approval authority belongs only to the SRE lead/Executive.',
    skills: [
      { id: 'prod_approve', name: 'Production Release Approval', description: 'Gate approval for production deployments', tags: ['release', 'approval', 'prod'] },
      { id: 'change_freeze', name: 'Change Freeze Decision', description: 'Deciding on code freezes/exceptions', tags: ['release', 'freeze'] },
    ],
    provider: { organization: 'Release Management (Glean)', url: 'https://example.local/release-approval' },
  },
  {
    key: 'finance',
    port: 5614,
    name: 'Finance Agent',
    department: 'Finance',
    platform: 'Copilot Studio',
    permission: ['Finance', 'Executive'],
    rating: 4.4,
    executionRating: 0.96,
    description: 'Inquiries about budgets, billing, and cost allocation. Note: even people involved in cloud/tool costs, financial data can only be used by Finance and Executive.',
    skills: [
      { id: 'budget', name: 'Budget Inquiry', description: 'Checking departmental budgets and execution status', tags: ['finance', 'budget'] },
      { id: 'billing', name: 'Billing/Cost Allocation', description: 'Checking allocation of SaaS/cloud costs', tags: ['finance', 'billing'] },
    ],
    provider: { organization: 'Finance (Copilot Studio)', url: 'https://example.local/finance' },
  },
  {
    key: 'exec',
    port: 5615,
    name: 'Executive Dashboard Agent',
    department: 'Executive',
    platform: 'In-house',
    permission: ['Executive'],
    rating: 4.5,
    executionRating: 0.97,
    description: 'Inquiries about company-wide KPIs and executive reports. Note: for Executive use only.',
    skills: [
      { id: 'company_kpi', name: 'Company-wide KPIs', description: 'Aggregating company-wide KPIs and OKRs', tags: ['exec', 'kpi'] },
      { id: 'board_report', name: 'Executive Reports', description: 'Summaries for the board of directors', tags: ['exec', 'report'] },
    ],
    provider: { organization: 'Executive Office (Glean)', url: 'https://example.local/exec' },
  },

  // ── Cross-cutting topics whose content varies by "company-wide baseline + role-specific" (compensation/bonus, HR policy) ──
  //    All have permission=Company-wide (informational reference). AI Buddy runs the company-wide version plus role-specific versions and integrates the answers.
  {
    key: 'comp_all',
    port: 5616,
    name: 'Company-wide Compensation & Bonus Policy Agent',
    department: 'HR',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.7,
    executionRating: 0.96,
    isCompanyWide: true,
    topic: 'compensation',
    description: 'Company-wide basic policy on compensation structure and bonus payouts (review periods, payout timing, common coefficients). The baseline shared across roles.',
    skills: [
      { id: 'bonus_baseline', name: 'Bonus Basic Policy', description: 'Calculating review periods, payout timing, and base amounts', tags: ['comp', 'bonus', 'baseline'] },
      { id: 'comp_bands', name: 'Compensation Bands', description: 'Company-wide compensation bands and revision cycle', tags: ['comp', 'salary'] },
    ],
    provider: { organization: 'People / Total Rewards (Glean)', url: 'https://example.local/comp-all' },
  },
  {
    key: 'comp_sales',
    port: 5617,
    name: 'Sales Incentive Agent',
    department: 'Sales',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.6,
    executionRating: 0.93,
    topic: 'compensation',
    description: 'Compensation differences for sales roles (commissions, SPIFFs, achievement-rate-linked pay). Bonuses are tied to revenue/pipeline attainment.',
    skills: [{ id: 'commission', name: 'Commission/SPIFF', description: 'Achievement-linked and accelerated rates', tags: ['comp', 'sales'] }],
    provider: { organization: 'Sales Comp (Glean)', url: 'https://example.local/comp-sales' },
  },
  {
    key: 'comp_eng',
    port: 5618,
    name: 'Engineer Compensation & Evaluation Agent',
    department: 'Engineering',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.7,
    executionRating: 0.94,
    topic: 'compensation',
    description: 'Compensation differences for engineering roles (grades/levels, stock refreshes, technical evaluation). Bonuses are tied to OKRs and evaluations.',
    skills: [{ id: 'eng_grade', name: 'Grade/RSU', description: 'Level bands and stock refreshes', tags: ['comp', 'eng'] }],
    provider: { organization: 'Eng Comp (Glean)', url: 'https://example.local/comp-eng' },
  },
  {
    key: 'comp_mgr',
    port: 5619,
    name: 'Manager & Executive Compensation Agent',
    department: 'Executive',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.5,
    executionRating: 0.95,
    topic: 'compensation',
    description: 'Compensation differences for managers and executives (performance-linked bonus coefficients, organizational goal attainment, LTI).',
    skills: [{ id: 'mgr_bonus', name: 'Performance-linked/LTI', description: 'Organizational-goal-linked coefficients and long-term incentives', tags: ['comp', 'manager'] }],
    provider: { organization: 'Exec Comp (Glean)', url: 'https://example.local/comp-mgr' },
  },
  {
    key: 'hr_policy_all',
    port: 5620,
    name: 'Company-wide HR Policy & Work Rules Agent',
    department: 'HR',
    platform: 'Copilot Studio',
    permission: ['Company-wide'],
    rating: 4.6,
    executionRating: 0.97,
    isCompanyWide: true,
    topic: 'hr_policy',
    description: 'The latest company-wide work rules, leave, work arrangements, and evaluation cycles. The baseline shared across roles.',
    skills: [{ id: 'work_rules', name: 'Work Rules', description: 'Shared rules on leave, work arrangements, and evaluations', tags: ['hr', 'policy'] }],
    provider: { organization: 'People / HR Policy (Microsoft Copilot Studio)', url: 'https://example.local/hr-all' },
  },
  {
    key: 'hr_policy_role',
    port: 5621,
    name: 'Role-based Work Arrangements Agent',
    department: 'HR',
    platform: 'Dify',
    permission: ['Company-wide'],
    rating: 4.5,
    executionRating: 0.94,
    topic: 'hr_policy',
    description: 'Differences in work arrangements by role and employment category (overtime treatment for managers/supervisors, discretionary/flextime work, on-call allowances, reduced hours).',
    skills: [{ id: 'role_rules', name: 'Role-based Differences', description: 'Differences in work arrangements by role', tags: ['hr', 'role'] }],
    provider: { organization: 'People / HR Policy (Dify)', url: 'https://example.local/hr-role' },
  },
  {
    key: 'expense_all',
    port: 5622,
    name: 'Company-wide Expense & Reimbursement Policy Agent',
    department: 'Accounting',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.6,
    executionRating: 0.96,
    isCompanyWide: true,
    topic: 'expense',
    description: 'Company-wide expense reimbursement rules (limits, approval flow, cutoff dates, receipt requirements). The baseline shared across roles.',
    skills: [{ id: 'expense_rules', name: 'Reimbursement Rules', description: 'Limits, approvals, cutoff dates, receipts', tags: ['expense', 'baseline'] }],
    provider: { organization: 'Finance Ops / Expense (Glean)', url: 'https://example.local/expense-all' },
  },
  {
    key: 'expense_sales',
    port: 5623,
    name: 'Sales Expense Agent',
    department: 'Sales',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.5,
    executionRating: 0.93,
    topic: 'expense',
    description: 'Expense differences for sales roles (limits and pre-approval for entertainment, hospitality, and travel expenses; handling of customer visits).',
    skills: [{ id: 'sales_expense', name: 'Entertainment/Travel', description: 'Limits and approvals for hospitality and travel', tags: ['expense', 'sales'] }],
    provider: { organization: 'Sales Ops (Glean)', url: 'https://example.local/expense-sales' },
  },
  {
    key: 'expense_eng',
    port: 5624,
    name: 'Engineer Expense Agent',
    department: 'Engineering',
    platform: 'In-house',
    permission: ['Company-wide'],
    rating: 4.6,
    executionRating: 0.95,
    topic: 'expense',
    description: 'Expense differences for engineering roles (equipment, cloud usage, learning/books, conference attendance support budgets).',
    skills: [{ id: 'eng_expense', name: 'Equipment/Learning Support', description: 'Support budgets for equipment, cloud, and learning', tags: ['expense', 'eng'] }],
    provider: { organization: 'Eng Ops (Glean)', url: 'https://example.local/expense-eng' },
  },
];

/** Build an A2A Agent Card (common format for registry registration and mock serving) from a spec */
export function cardFor(spec) {
  return {
    protocolVersion: '0.2.5',
    name: spec.name,
    description: spec.description,
    version: '1.0.0',
    provider: spec.provider,
    url: `http://localhost:${spec.port}/a2a`,
    capabilities: { streaming: true, pushNotifications: false },
    defaultInputModes: ['text/plain'],
    defaultOutputModes: ['text/plain'],
    skills: spec.skills,
  };
}
